service: ngx-portfolio
plugins:
  - serverless-offline
  - serverless-express
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  memorySize: 192
  timeout: 10
  profile: danduh
  region: us-west-2

package:
  patterns:
    - "!/**"
    - "node_modules/@vendia/serverless-express/**"
    - "dist/**"
    - "lambda.js"
  exclude:
    - apps/**
    - devops/**
    - libs/**
    - tools/**
    - src/**
    - node_modules/**
    - .git/**
    - .angular/**
    - e2e/**
    - coverage/**
    ##- '!src/assets/**'
    - '!node_modules/aws-serverless-express/**'
    - '!node_modules/binary-case/**'
    - '!node_modules/type-is/**'
    - '!node_modules/media-typer/**'
    - '!node_modules/mime-types/**'
    - '!node_modules/mime-db/**'
functions:
  api:
    handler: lambda.ssrserverless
    events:
      - http: ANY /
      - http: GET /{proxy+}
